# Generated by Django 4.1 on 2022-10-17 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistemaLicencia', '0002_remove_cuestionario_id_cuestionario_idcuestionario_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='anteojos',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='persona',
            name='examenRendidos',
            field=models.IntegerField(default=0),
        ),
    ]
