# Generated by Django 4.1 on 2022-10-20 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistemaLicencia', '0003_alter_persona_anteojos_alter_persona_examenrendidos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='examen',
            name='idcuest',
        ),
        migrations.AddField(
            model_name='examen',
            name='nombreCuest',
            field=models.CharField(default='Examen Teorico', max_length=50),
        ),
        migrations.AlterField(
            model_name='examen',
            name='rendido',
            field=models.BooleanField(default=False),
        ),
    ]
